"""create tables

Revision ID: e88d0ebe9ac4
Revises: 202d695549f5
Create Date: 2020-08-29 23:00:10.296297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e88d0ebe9ac4'
down_revision = '202d695549f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('image', sa.String(), nullable=True))
    op.drop_column('visits', 'images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('images', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=True))
    op.drop_column('visits', 'image')
    # ### end Alembic commands ###
